### ISSUE TITLE
代码复现问题

### ISSUE THREAD

**Issue by Accept111** [Jaron-U/conditional_diffusion_compression#1]
作者您好！
我在运行您这段代码的时候出现了问题。这是终端信息。

model name: image-l2-use_weight5-vimeo-d64-t3-b1e-05-x-cosine-01-float32-aux0
sampling loop time step: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 10.78it/s]
training completed

可以看到根本就没开始训练，能帮我看一下原因嘛？
感谢作者回答！

**Comment by Accept111** [comment]
我找到问题了，是代码里的n_step太小，请问作者能否给一份最优的参数？

**Comment by Jaron-U** [comment]
请参考官方仓库：https://github.com/buggyyang/CDC_compression
